#define { package-version: 2.32.3.1; }

#define { author-version: "2.32.3"; }

#define { outercurve-publickeytoken: "1e373a58e25250cb"; }

#define { deps-publickeytoken: "345efd3e6aa00ef7"; }

#define { libintl-dep-version: "0.18.1"; }

#define { libintl-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { libffi-dep-version: "3.0.10"; }

#define { libffi-dep-publickeytoken: "${deps-publickeytoken}"; }
